### ISSUE TITLE
rematch

### ISSUE THREAD

**Issue by wocswang** [qyhever/e-admin-react#4]
你好，这个项目怎么没有考虑再用rematch这种的状态管理，而是用了mobx,我是最近在学习这块，rematch很像vuex，因为之前都是写的vue的项目

**Comment by qyhever** [comment]
如果你是 vuex 过来的，rematch 确实上手快。其实用 mobx 也只是尝试而已， redux 毕竟用的够多了。然后 redux 提倡纯函数的方式，mobx 是将状态包装成可观察对象，一旦状态更新，就能自动更新，这点更像 vue 的响应原理。
